### ISSUE TITLE
[BUG]  点击搜索框内容后，搜索框可能不会消失

### ISSUE THREAD

**Issue by ttimochan** [nx-space/nx-theme-Single#18]
## 环境

System  :  Windows 11 
Chrome Version ：104.0.5112.102

## 问题

在搜索框内跳转到目标页面以后，可能存在意外的不消失问题，在 Windows Chrome 上需要点击搜索框上/下面的文章内容才会消失，左面和右面则不会，即点击侧边不会消失

![](https://user-images.githubusercontent.com/91021824/185757241-4e8a4a41-66c3-43b3-8d4d-52f130633c4b.png)

在图片中，这个搜索框不会消失，且需要点击上下边内容才会消失，侧边不会

**Comment by wibus-wee** [comment]
<img width="1526" alt="截屏2022-08-21 22 07 53" src="https://user-images.githubusercontent.com/62133302/185794992-b69b1935-2ddc-4ce1-a1e9-2bb052843c2b.png">

组件宽度如图所示，原因在此
