### ISSUE TITLE
[Bug] 图标样式无法正常加载

### ISSUE THREAD

**Issue by wibus-wee** [nx-space/nx-theme-Single#30]
控制台输出以下内容：

```﻿
Refused to apply style from 'https://fastly.jsdelivr.net/gh/FortAwesome/Font-Awesome/css/font-awesome.min.css' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

链接访问后发现提示 `Package size exceeded the configured limit of 50 MB. Try https://github.com/FortAwesome/Font-Awesome/tree/6.2.0/css/font-awesome.min.css instead.`

**Comment by ttimochan** [comment]
https://github.com/nx-space/nx-theme-Single/pull/31
